name: Auto Fetch Proxies

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install aiohttp aiohttp-socks geoip2

      # TỰ ĐỘNG TẢI DATABASE GEOIP VỀ CHẠY LOCAL
      - name: Download Local GeoIP Databases
        run: |
          mkdir -p geoip
          wget -q https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-Country.mmdb -O geoip/GeoLite2-Country.mmdb
          wget -q https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb -O geoip/GeoLite2-ASN.mmdb

      - name: Run script
        run: python fetch_proxies.py

      - name: Commit and push safely
        run: |
          cp proxies.txt proxies.txt.bak
          git fetch origin main
          git reset --hard origin/main
          mv proxies.txt.bak proxies.txt
          
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add proxies.txt
          
          if ! git diff --staged --quiet; then
            git commit -m "🤖 Update proxy list [skip ci]"
            git push origin main
          else
            echo "Không có thay đổi dữ liệu."
          fi
